dist: xenial
sudo: required
services:
  - docker

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
env:
  - HTCONDOR_VERSION=8.8
  - HTCONDOR_VERSION=8.9

matrix:
  fast_finish: true

install:
  - travis_retry docker build -t htmap-test --file docker/Dockerfile --build-arg HTCONDOR_VERSION --build-arg PYTHON_VERSION=$TRAVIS_PYTHON_VERSION .

script:
  - travis_retry docker run htmap-test tests/travis.sh
